restaurante/config/routes.rb
Rails.application.routes.draw do

  resources :evaluates
  resources :payments
  resources :categories
  root 'bills#new'

  resources :ingredients
  resources :items
  resources :orders
  resources :bills

  get '/menu', to: "items#menu"
  match 'order_item', to: 'items#order_item', via: [:get, :post]
  post 'add_order', to: 'orders#add_order'
  match 'edit_order_items', to: 'items#edit_order_items', via: [:get, :post]
  post 'amount_change', to: 'ingredients#amount_change'
  post 'back_to_menu', to: 'orders#back_to_menu'
  match 'close_bill', to: 'bills#close_bill', via: [:get, :post]
  match 'pay_bill', to: 'bills#pay_bill', via: [:get, :post]
  match 'payment_type', to: 'payments#payment_type', via: [:get, :post]
  match 'payment_type2', to: 'payments#payment_type2', via: [:get, :post]
  match 'payment_instructions', to: 'payments#payment_instructions', via: [:get, :post]
  match 'end_eval', to: 'evaluates#end_eval', via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

restaurante/app/models/evaluate.rb
class Evaluate < ApplicationRecord
end

restaurante/app/controllers/evaluates_controller.rb
class EvaluatesController < ApplicationController
  before_action :set_evaluate, only: [:show, :edit, :update, :destroy]

  # GET /evaluates
  # GET /evaluates.json
  def index
    @evaluates = Evaluate.all
  end

  # GET /evaluates/1
  # GET /evaluates/1.json
  def show
  end

  # GET /evaluates/new
  def new
    @evaluate = Evaluate.new
  end

  def end_eval
    @eval = params[:eval]
    @evaluate = Evaluate.new(
      :value => @eval
    )
    @evaluate.save
  end

  # GET /evaluates/1/edit
  def edit
  end

  # POST /evaluates
  # POST /evaluates.json
  def create
    @evaluate = Evaluate.new(evaluate_params)

    respond_to do |format|
      if @evaluate.save
        format.html { redirect_to @evaluate, notice: 'Evaluate was successfully created.' }
        format.json { render :show, status: :created, location: @evaluate }
      else
        format.html { render :new }
        format.json { render json: @evaluate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluates/1
  # PATCH/PUT /evaluates/1.json
  def update
    respond_to do |format|
      if @evaluate.update(evaluate_params)
        format.html { redirect_to @evaluate, notice: 'Evaluate was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluate }
      else
        format.html { render :edit }
        format.json { render json: @evaluate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluates/1
  # DELETE /evaluates/1.json
  def destroy
    @evaluate.destroy
    respond_to do |format|
      format.html { redirect_to evaluates_url, notice: 'Evaluate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluate
      @evaluate = Evaluate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluate_params
      params.require(:evaluate).permit(:value)
    end
end

restaurante/app/helpers/evaluates_helper.rb
module EvaluatesHelper
end

restaurante/app/views/evaluates/_form.html.erb
<%= form_with(model: evaluate, local: true) do |form| %>
  <% if evaluate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluate.errors.count, "error") %> prohibited this evaluate from being saved:</h2>

      <ul>
      <% evaluate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

restaurante/app/views/evaluates/edit.html.erb
<h1>Editing Evaluate</h1>

<%= render 'form', evaluate: @evaluate %>

<%= link_to 'Show', @evaluate %> |
<%= link_to 'Back', evaluates_path %>

restaurante/app/views/evaluates/end_eval.html.erb
<div style="width:50%; margin:0 auto;font-size:50px;text-align:center;color:green;font-weight:bold;">
  <br><br><br><br>Obrigado! Volte sempre!
</div>

<%= button_to '', root_path, :style => "position: absolute; right: 0; bottom: 0; background-color:#CCC;", :method => :get %>

restaurante/app/views/evaluates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluates</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluates.each do |evaluate| %>
      <tr>
        <td><%= evaluate.value %></td>
        <td><%= link_to 'Show', evaluate %></td>
        <td><%= link_to 'Edit', edit_evaluate_path(evaluate) %></td>
        <td><%= link_to 'Destroy', evaluate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluate', new_evaluate_path %>

restaurante/app/views/evaluates/new.html.erb
<h1>New Evaluate</h1>

<%= render 'form', evaluate: @evaluate %>

<%= link_to 'Back', evaluates_path %>

restaurante/app/views/evaluates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @evaluate.value %>
</p>

<%= link_to 'Edit', edit_evaluate_path(@evaluate) %> |
<%= link_to 'Back', evaluates_path %>