restaurante/config/routes.rb
Rails.application.routes.draw do

  resources :evaluates
  resources :payments
  resources :categories
  root 'bills#new'

  resources :ingredients
  resources :items
  resources :orders
  resources :bills

  get '/menu', to: "items#menu"
  match 'order_item', to: 'items#order_item', via: [:get, :post]
  post 'add_order', to: 'orders#add_order'
  match 'edit_order_items', to: 'items#edit_order_items', via: [:get, :post]
  post 'amount_change', to: 'ingredients#amount_change'
  post 'back_to_menu', to: 'orders#back_to_menu'
  match 'close_bill', to: 'bills#close_bill', via: [:get, :post]
  match 'pay_bill', to: 'bills#pay_bill', via: [:get, :post]
  match 'payment_type', to: 'payments#payment_type', via: [:get, :post]
  match 'payment_type2', to: 'payments#payment_type2', via: [:get, :post]
  match 'payment_instructions', to: 'payments#payment_instructions', via: [:get, :post]
  match 'end_eval', to: 'evaluates#end_eval', via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

restaurante/app/models/payment.rb
class Payment < ApplicationRecord
end

restaurante/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  def payment_type
    @value = params[:value]
    @bill = params[:bill_id]
    @card = params[:card]
    @option = params[:option]
    @payment = Payment.new(
      :bill_id => @bill,
      :option => @option,
      :card => @card
    )
    @payment.save
  end

  def payment_type2
    @value = params[:value]
    @bill = params[:bill_id]
    @card = params[:card]
    @option = params[:option]
    @payment = Payment.new(
      :bill_id => @bill,
      :option => @option,
      :card => @card
    )
    @payment.save
  end

  def payment_instructions
    @value = params[:value]
    @bill = params[:bill_id]
    @card = params[:card]
    @option = params[:option]
    @payment = Payment.where(bill_id: @bill).limit(1)
    @payment[0].option = @option
    @payment[0].save
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:card, :option)
    end
end

restaurante/app/helpers/payments_helper.rb
module PaymentsHelper
end

restaurante/app/views/payments/_evaluation.html.erb
<hr />
<span style="font-size:18px;">
  Avalie o nosso sistema!
</span>

<br><br>
<table width="100%">
  <tr>
    <td>
      <%= button_to 'Muito ruim', end_eval_path, :class => 'btn btn-danger btn-eval' %>
    </td>
    <td>
      <%= button_to 'Ruim', end_eval_path, :class => 'btn btn-warning btn-eval' %>
    </td>
    <td>
      <%= button_to 'Regular', end_eval_path, :class => 'btn btn-secondary btn-eval' %>
    </td>
    <td>
      <%= button_to 'Bom', end_eval_path, :class => 'btn btn-primary btn-eval' %>
    </td>
    <td>
      <%= button_to 'Excelente', end_eval_path, :class => 'btn btn-success btn-eval' %>
    </td>
  </tr>
</table>

restaurante/app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card %>
    <%= form.text_field :card %>
  </div>

  <div class="field">
    <%= form.label :option %>
    <%= form.number_field :option %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

restaurante/app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

restaurante/app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.card %></td>
        <td><%= payment.option %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

restaurante/app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

restaurante/app/views/payments/payment_instructions.html.erb
<div class="closed-bill">
  <table width="100%">
    <tr>
      <td colspan="2" class="closed-bill-total-value">
        Total: R$ <%= @value.to_s.sub(".",",") %>
      </td>
    </tr>
  </table>
  <br>
  <span style="font-size:25px;">
    Você escolheu pagar com
  </span>
  <%= image_tag("#{@card}.jpg", :style => "width: 15%;") %>
  <span style="font-size:25px;">
    <% if @option == '1' %>
      <%= "(Débito)" %>
    <% else %>
      <%= "(Crédito)" %>
    <% end %>
  </span>

  <table width="100%">
    <tr>
      <td colspan="2">
        <br><br>
        <span style="font-size:18px;">
          Instruções:<br><br>
          1 - Insira o seu cartão na máquina<br>
          2 - Aguarde 5 segundos<br>
          3 - Digite a sua senha e aperte o botão "Confirma"
        </span>
        <br><br>
      </td>
    </tr>
    <tr>
      <td>
        <%= render 'evaluation' %>
      </td>
    </tr>
  </table>
</div>

restaurante/app/views/payments/payment_type.html.erb
<div class="closed-bill">
  <table width="100%">
    <tr>
      <td colspan="2" class="closed-bill-total-value">
        Total: R$ <%= @value.to_s.sub(".",",") %>
      </td>
    </tr>
  </table>
  <br><br>
  <span style="font-size:25px;">
    Você escolheu pagar com
  </span>
  <%= image_tag("#{@card}.jpg", :style => "width: 15%;") %>

  <br><br>

  <table width="100%">
    <tr>
      <td colspan="2">
        <br><br>
        <span style="font-size:18px;">
          Débito ou crédito? Toque para escolher.
        </span>
        <br><br>
      </td>
    </tr>
    <tr>
      <td style="width:50%;">
        <%= button_to 'Débito', payment_instructions_path(option: 1, card: @card, bill_id: @bill, value: @value), :method => :post, :class => 'btn btn-primary btn-card-type' %>
      </td>
      <td>
        <%= button_to 'Crédito', payment_instructions_path(option: 2, card: @card, bill_id: @bill, value: @value), :method => :post, :class => 'btn btn-primary btn-card-type' %>
      </td>
    </tr>
  </table>
</div>

restaurante/app/views/payments/payment_type2.html.erb
<div class="closed-bill">
  <table width="100%">
    <tr>
      <td colspan="2" class="closed-bill-total-value">
        Total: R$ <%= @value.to_s.sub(".",",") %>
      </td>
    </tr>
  </table>
  <br><br>
  <span style="font-size:25px;">
    Você escolheu pagar em <span style="color:green;">dinheiro</span>!
  </span>

  <br><br>

  <table width="100%">
    <tr>
      <td colspan="2">
        <br><br>
        <span style="font-size:18px;">
          Um garçom está se dirigindo à sua mesa. Aguarde!
        </span>
        <br><br>
      </td>
    </tr>
    <tr>
      <td>
        <%= render 'evaluation' %>
      </td>
    </tr>
  </table>
</div>

restaurante/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card:</strong>
  <%= @payment.card %>
</p>

<p>
  <strong>Option:</strong>
  <%= @payment.option %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>