restaurante/config/routes.rb
Rails.application.routes.draw do

  resources :evaluates
  resources :payments
  resources :categories
  root 'bills#new'

  resources :ingredients
  resources :items
  resources :orders
  resources :bills

  get '/menu', to: "items#menu"
  match 'order_item', to: 'items#order_item', via: [:get, :post]
  post 'add_order', to: 'orders#add_order'
  match 'edit_order_items', to: 'items#edit_order_items', via: [:get, :post]
  post 'amount_change', to: 'ingredients#amount_change'
  post 'back_to_menu', to: 'orders#back_to_menu'
  match 'close_bill', to: 'bills#close_bill', via: [:get, :post]
  match 'pay_bill', to: 'bills#pay_bill', via: [:get, :post]
  match 'payment_type', to: 'payments#payment_type', via: [:get, :post]
  match 'payment_type2', to: 'payments#payment_type2', via: [:get, :post]
  match 'payment_instructions', to: 'payments#payment_instructions', via: [:get, :post]
  match 'end_eval', to: 'evaluates#end_eval', via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

restaurante/app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :ingredients
end

restaurante/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:new, :edit, :menu]
  # load_resource
  # GET /items
  # GET /items.json
  def index
    @items = Item.all.order(category_id: :asc)
  end

  # Diferente de Index pois aqui é para visão do usuário e não gerenciamento interno de items
  def menu
    @bill = params[:bill_id]
    @items = Item.all
    @orders = Order.where(bill_id: @bill)
    @ingredients = Ingredient.all
    @ingredients.each do |ing|
      ing.contained = 1
      ing.save
    end
  end

  def edit_order_items
    @bill = params[:bill_id]
    @ingredients = Ingredient.all.where(item_id: params[:item_id])
    @item = Item.find(params[:item_id])
  end

  def order_item
    redirect_back(fallback_location: root_path)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_categories
      @categories = Category.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :value, :category_id, :photo)
    end
end

restaurante/app/helpers/items_helper.rb
module ItemsHelper
end

restaurante/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, type: 'numeric' %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %><br>
    <% @categories.each do |category| %>
        <%= "#{category.id}-#{category.title} " %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

restaurante/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

restaurante/app/views/items/edit_order_items.html.erb
<table>
  <tr>
    <td>
      <h1><%= @item.name %></h1>
      <%= @item.description %>
      <br><br>
    </td>
    <td>
    </td>
  </tr>
  <tr>
    <td>
      <table>
      <% removeds = 0 %>
      <% obs = [] %>
      <% @ingredients.order(name: :asc).each do |ing| %>
        <tr>
          <td class="menu-item-change-ingredients-name">
            <%= ing.name %>
          </td>
          <% if ing.contained == 0 %>
            <% removeds += 1 %>
            <% cont = 1 %>
            <% butt = "Adicionar" %>
            <% btn_class = "btn btn-success" %>
            <% check = "uncheck.png" %>
          <% else %>
            <% cont = 0 %>
            <% butt = "Remover" %>
            <% btn_class = "btn btn-danger" %>
            <% check = "check.png" %>
          <% end %>
          <td class="menu-item-change-ingredients-check-img">
            <%= image_tag(check, :style => "width: 80%;") %>
          </td>
          <td>
            <%= button_to butt, amount_change_path(contained: cont, id: ing.id), :method => :post, :class => btn_class %>
          </td>
        </tr>
      <% end %>
      </table>
    </td>
    <td class="menu-item-change-ingredients-resume">
      <%= @item.name %><br><br>
      <% if removeds == 0 %>
        <div class="menu-item-change-ingredients-completed">
          <% if @item.category_id == 4 %>
            <%= "Com gelo e limão!" %>
          <% else %>
            <%= "COMPLETO!" %>
          <% end %>
        </div>
      <% else %>
        <% @ingredients.where(contained: 0, item_id: @item.id).each do |ing| %>
          <div class="menu-item-change-ingredients-removeds">
            <%= "Sem #{ing.name}" %>
          </div>
        <% end %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
      <%= button_to 'Pedir', add_order_path(name: @item.name, value: @item.value, :description => @item.description, :obs => '', :qtd => 1, :bill_id => @bill, :item_id => @item.id), :method => :post, :class => 'btn btn-success menu-item-btn' %>
      <br />
      <%= button_to 'Voltar ao menu', back_to_menu_path(:bill_id => @bill), :method => :post, :class => 'btn btn-primary menu-item-btn' %>
    </td>
  </tr>
</table>

restaurante/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Valor</th>
      <th>Categoria</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <% item_value = "%0.02f" % item.value.round(2) %>
        <td>R$ <%= item_value.to_s.sub(".",",") %> </td>
        <td><%= item.category_id %></td>
        <td><%= item.photo %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

restaurante/app/views/items/menu.html.erb
<div class="menu-my-orders">
  <h2> Minha comanda </h2>
  <h6> <%= "Mesa 01 - Comanda Nº #{@bill}" %> </h6>
  <table width="100%">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.order(created_at: :asc).each do |order| %>
        <tr>
          <td class="menu-my-orders-each">
            <span class="menu-my-order-name"><%= order.name %></span>
            <br>
            <span class="menu-my-order-obs">
              <%= "(#{order.obs})" if order.obs != "" %>
            </span>
            <span class="menu-my-order-value">
                <% if order.obs != "" %>
                  <br>
                <% end %>
                <% order_value = "%0.02f" % order.value.round(2) %>
                R$<%= order_value.to_s.sub(".",",") %>
            </span>
          </td>
          <td class="menu-my-orders-each" style="width:90px;">
            <span class="menu-my-order-status-<%=order.status%>">
                <% if order.status == 0 %>
                  Solicitado
                <% elsif order.status == 1 %>
                  Em preparo
                <% elsif order.status == 2 %>
                  Pronto!
                <% end %>
                <!-- <img src="images/" -->
            </span>
          </td>
        </tr>
      <% end %>
        <tr>
          <td class="menu-my-orders-total">
            <% if @orders.sum(:value) != 0 %>
              <% orders_total = "%0.02f" % @orders.sum(:value).round(2) %>
              <span class="menu-my-orders-total-label">R$ <%= orders_total.to_s.sub(".",",") %></span>
            <% else %>
              Faça seu primeiro pedido!
            <% end %>
          </td>
        </tr>
        <tr>
          <td>
            <% if @orders.sum(:value) != 0 %>
              <%= button_to 'Fechar comanda', close_bill_path(:bill_id => @bill), :method => :post, :class => 'btn btn-warning' %>
            <% end %>
          </td>
        </tr>
    </tbody>
  </table>
</div>


<div class="menu-items">
  <h2> Cardápio </h2>
  <table width="100%">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="cardapio-categoria">
          Lanches
        </td>
      </tr>
      <% @items.where(category_id: 3).each do |item| %>
          <% if item.photo %>
            <% img_item = "items/#{item.photo}" %>
          <% else %>
            <% img_item = "items/brasserie_prato_dez.jpg" %>
          <% end %>
          <tr>
            <td class="menu-item-column-photo"><%= image_tag(img_item, :style => "width: 100%;") %></td>
            <td>
              <div class="menu-item-name"><%= item.name %></div>
              <div class="menu-item-description"><%= item.description %></div>
            </td>
            <% item_value = "%0.02f" % item.value.round(2) %>
            <td class="menu-item-value">R$<%= item_value.to_s.sub(".",",") %> </td>
            <td>
              <% if [1,2,3,4,6].include?(item.category_id) %>
                <%= button_to 'Ver / modificar', edit_order_items_path(item_id: item.id, bill_id: @bill), :method => :post, :class => 'btn btn-primary menu-item-btn' %>
              <% end %>
            </td>
            <td><%= button_to 'Pedir', add_order_path(name: item.name, value: item.value, :description => item.description, :obs => '', :qtd => 1, :bill_id => @bill, :item_id => item.id), :method => :post, :class => 'btn btn-success menu-item-btn' %>
          </tr>
        <% end %>

        <tr>
          <td class="cardapio-categoria">
            Bebidas
          </td>
        </tr>
      <% @items.where(category_id: 4).each do |item| %>
          <% if item.photo %>
            <% img_item = "items/#{item.photo}" %>
          <% else %>
            <% img_item = "items/brasserie_prato_dez.jpg" %>
          <% end %>
          <tr>
            <td class="menu-item-column-photo"><%= image_tag(img_item, :style => "width: 100%;") %></td>
            <td>
              <div class="menu-item-name"><%= item.name %></div>
              <div class="menu-item-description"><%= item.description %></div>
            </td>
            <% item_value = "%0.02f" % item.value.round(2) %>
            <td class="menu-item-value">R$<%= item_value.to_s.sub(".",",") %> </td>
            <td>
              <% if [1,2,3,4,6].include?(item.category_id) %>
                <%= button_to 'Ver / modificar', edit_order_items_path(item_id: item.id, bill_id: @bill), :method => :post, :class => 'btn btn-primary menu-item-btn' %>
              <% end %>
            </td>
            <td><%= button_to 'Pedir', add_order_path(name: item.name, value: item.value, :description => item.description, :obs => '', :qtd => 1, :bill_id => @bill, :item_id => item.id), :method => :post, :class => 'btn btn-success menu-item-btn' %>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

<script>

$(document).ready(function () {
  $("a[data-confirm]").data({
    "confirm-fade": true,
    "confirm-title": "Call to Buzz"
  });
  $("a[data-method=delete]").data({
    "confirm-title": "Warning",
    "confirm-cancel": "Cancel",
    "confirm-cancel-class": "btn-cancel",
    "confirm-proceed": "Delete",
    "confirm-proceed-class": "btn-danger"
  });
});

</script>

restaurante/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

restaurante/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @item.value %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @item.photo %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>