restaurante/config/routes.rb
Rails.application.routes.draw do

  resources :evaluates
  resources :payments
  resources :categories
  root 'bills#new'

  resources :ingredients
  resources :items
  resources :orders
  resources :bills

  get '/menu', to: "items#menu"
  match 'order_item', to: 'items#order_item', via: [:get, :post]
  post 'add_order', to: 'orders#add_order'
  match 'edit_order_items', to: 'items#edit_order_items', via: [:get, :post]
  post 'amount_change', to: 'ingredients#amount_change'
  post 'back_to_menu', to: 'orders#back_to_menu'
  match 'close_bill', to: 'bills#close_bill', via: [:get, :post]
  match 'pay_bill', to: 'bills#pay_bill', via: [:get, :post]
  match 'payment_type', to: 'payments#payment_type', via: [:get, :post]
  match 'payment_type2', to: 'payments#payment_type2', via: [:get, :post]
  match 'payment_instructions', to: 'payments#payment_instructions', via: [:get, :post]
  match 'end_eval', to: 'evaluates#end_eval', via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

restaurante/app/models/bill.rb
class Bill < ApplicationRecord
  has_many :orders
end

restaurante/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def welcome
  end

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to menu_path(:bill_id => @bill.id)
    else
      format.html { render :new }
      format.json { render json: @bill.errors, status: :unprocessable_entity }
    end
  end

  def close_bill
    @bill = params[:bill_id]
    @orders = Order.all.where(bill_id: @bill)
  end

  def pay_bill
    @value = params[:total_value]
  end


  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:value, :status)
    end
end

restaurante/app/helpers/bills_helper.rb
module BillsHelper
end

restaurante/app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true, :html => {:style => 'width: 50%; margin: 0 auto;'}) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :value, value: 0, type: 'hidden' %>
  </div>

  <div class="field">
    <%= form.text_field :status, value: 'aberta', type: 'hidden' %>
  </div>

  <div class="actions">
    <%= form.submit 'FAZER PEDIDO', :class => 'new_bill_button btn btn-success' %>
  </div>
<% end %>

restaurante/app/views/bills/close_bill.html.erb
<div class="closed-bill">
  <table width="100%">
    <tr>
      <td colspan="2" class="closed-bill-total-value">
        <% orders_total = "%0.02f" % @orders.sum(:value).round(2) %>
        Total: R$ <%= orders_total.to_s.sub(".",",") %>
      </td>
    </tr>
  </table>

  <div class="closed-bill-payment-label">
    Forma de pagamento: <br><br> Toque em uma das opções abaixo!
  </div>

  <div>
    <%= link_to image_tag("master.jpg", :style => "width: 15%;"), payment_type_path(:value => orders_total, :bill_id => @bill, :card => "master") %>
    <%= link_to image_tag("visa.jpg", :style => "width: 15%;"), payment_type_path(:value => orders_total, :bill_id => @bill, :card => "visa") %>
    <%= link_to image_tag("hiper.jpg", :style => "width: 15%;"), payment_type_path(:value => orders_total, :bill_id => @bill, :card => "hiper") %>
    <%= link_to image_tag("elo.jpg", :style => "width: 15%;"), payment_type_path(:value => orders_total, :bill_id => @bill, :card => "elo") %>
    <%= link_to image_tag("american.png", :style => "width: 12%;"), payment_type_path(:value => orders_total, :bill_id => @bill, :card => "american") %>
    <%= link_to image_tag("cash.jpg", :style => "width: 10%;"), payment_type2_path(:value => orders_total, :bill_id => @bill, :card => "cash") %>
  </div>

</div>

restaurante/app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

restaurante/app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.value %></td>
        <td><%= bill.status %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

restaurante/app/views/bills/new.html.erb
<div class="new_bill_label"></div>

<div style="border:0px solid red;">
<%= render 'form', bill: @bill %>
</div>

<div style="width:25%; border:0px solid blue; margin-right:7%; margin-top:-4%; float:right; position: relative;">
  <%= image_tag("touch-icon.png", :alt => "Touch here", :style => "width: 50%; transform: rotate(45deg);") %>
  <br><span style="margin-left:10%;">Toque para começar</span>
</div>


<!-- <%= link_to 'Back', bills_path %> -->

restaurante/app/views/bills/pay_bill.html.erb
Tela de pagamento
<br><br>
Valor total: R$ <%= @value.to_s.sub(".",",") %>

restaurante/app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @bill.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bill.status %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

restaurante/app/views/bills/welcome.html.erb
<%= link_to 'Abrir comanda', items_path, class: 'new_bill_button' %>